# Generated by Django 5.2.4 on 2026-08-18 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_changehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_success', 'Pomyślne logowanie'), ('login_failure', 'Nieudana próba logowania'), ('login_locked', 'Konto zablokowane (zbyt wiele prób)'), ('permission_change', 'Zmiana uprawnień'), ('password_change', 'Zmiana hasła'), ('user_created', 'Utworzono użytkownika'), ('user_deleted', 'Usunięto użytkownika'), ('suspicious_activity', 'Podejrzana aktywność')], max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='assets_secu_created_a9bb30_idx'), models.Index(fields=['user', '-created_at'], name='assets_secu_user_id_11972b_idx'), models.Index(fields=['event_type', '-created_at'], name='assets_secu_event_t_faf5e4_idx')],
            },
        ),
    ]
